server:
  port: 8000

spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

  #配置 Jpa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

  redis:
    #数据库索引
    database: 0
    host: 129.28.187.140
    port: 6379
    password: hanhuibing
    #连接超时时间
    timeout: 5000
  application:
    name: dolphin-manager
#  安全校验
  security:
    user:
      name: user
      password: hanhuibing

#七牛云
qiniu:
  # 文件大小 /M
  max-size: 15

#邮箱验证码有效时间/分钟
code:
  expiration: 5

#登录图形验证码有效时间/分钟
loginCode:
  expiration: 2

#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://user:hanhuibing@com.dolphin.eureka2:9002/eureka/, http://user:hanhuibing@com.dolphin.eureka1:9001/eureka/
  instance:
    hostname: dolphin-manager
    health-check-url-path: /actuator/health
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

logging:
  file: /var/log/sample-boot-application.log
  pattern:
    file: clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx
management:
  endpoints:
    web:
      exposure:
        include: "*"